/*
Navicat MySQL Data Transfer

Source Server         : local
Source Server Version : 50505
Source Host           : localhost:3306
Source Database       : pa_2023

Target Server Type    : MYSQL
Target Server Version : 50505
File Encoding         : 65001

Date: 2023-11-20 09:27:50
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for `question_pa`
-- ----------------------------
DROP TABLE IF EXISTS `question_pa`;
CREATE TABLE `question_pa` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `group` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `title` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `title_en` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `item` text COLLATE latin1_general_ci DEFAULT NULL,
  `item_en` text COLLATE latin1_general_ci DEFAULT NULL,
  `role` varchar(15) COLLATE latin1_general_ci NOT NULL DEFAULT 'all',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=73 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

-- ----------------------------
-- Records of question_pa
-- ----------------------------
INSERT INTO question_pa VALUES ('1', 'synergized', 'culture', 'SYNERGIZED TEAM', 'SYNERGIZED TEAM', 'Mampu berpartisipasi aktif dalam kelompok, seperti mengutarakan opini dan pandangan', 'Mampu berpartisipasi aktif dalam kelompok, seperti mengutarakan opini dan pandangan (eng)', 'nonstaff');
INSERT INTO question_pa VALUES ('2', 'synergized', 'culture', 'SYNERGIZED TEAM', 'SYNERGIZED TEAM', 'Mampu mendengarkan opini anggota kelompoknya dengan positif ', 'Mampu mendengarkan opini anggota kelompoknya dengan positif  (eng)', 'nonstaff');
INSERT INTO question_pa VALUES ('3', 'synergized', 'culture', 'SYNERGIZED TEAM', 'SYNERGIZED TEAM', 'Mampu mengkomunikasikan hambatan yang dialami dalam bekerja', 'Mampu mengkomunikasikan hambatan yang dialami dalam bekerja (eng)', 'nonstaff');
INSERT INTO question_pa VALUES ('4', 'synergized', 'culture', 'SYNERGIZED TEAM', 'SYNERGIZED TEAM', 'Secara konsisten mampu mengajak orang lain untuk saling menghargai dan bekerja sama dalam mencapai tujuan bersama', 'Secara konsisten mampu mengajak orang lain untuk saling menghargai dan bekerja sama dalam mencapai tujuan bersama (eng)', 'staff');
INSERT INTO question_pa VALUES ('5', 'synergized', 'culture', 'SYNERGIZED TEAM', 'SYNERGIZED TEAM', 'Mampu membagikan informasi yang relevan sehubungan pekerjaan dalam tim', 'Mampu membagikan informasi yang relevan sehubungan pekerjaan dalam tim (eng)', 'staff');
INSERT INTO question_pa VALUES ('6', 'synergized', 'culture', 'SYNERGIZED TEAM', 'SYNERGIZED TEAM', 'Mampu menunjukkan kepekaan terhadap kebutuhan kerja anggota kelompoknya', 'Mampu menunjukkan kepekaan terhadap kebutuhan kerja anggota kelompoknya (eng)', 'staff');
INSERT INTO question_pa VALUES ('7', 'synergized', 'culture', 'SYNERGIZED TEAM', 'SYNERGIZED TEAM', 'Mampu membantu, mendorong dan membimbing rekan kerja dan orang lain untuk bekerja sama', 'Mampu membantu, mendorong dan membimbing rekan kerja dan orang lain untuk bekerja sama (eng)', 'staffb');
INSERT INTO question_pa VALUES ('8', 'synergized', 'culture', 'SYNERGIZED TEAM', 'SYNERGIZED TEAM', 'Mampu menerapkan komunikasi dua arah dalam bekerja', 'Mampu menerapkan komunikasi dua arah dalam bekerja (eng)', 'staffb');
INSERT INTO question_pa VALUES ('9', 'synergized', 'culture', 'SYNERGIZED TEAM', 'SYNERGIZED TEAM', 'Mampu memberikan motivasi dan mempertahankan semangat timnya', 'Mampu memberikan motivasi dan mempertahankan semangat timnya (eng)', 'staffb');
INSERT INTO question_pa VALUES ('10', 'synergized', 'culture', 'SYNERGIZED TEAM', 'SYNERGIZED TEAM', 'Mampu menjadi role model dalam membangun dan menerapkan budaya transfer pengetahuan dalam departemen atau divisi yang dipimpin', 'Mampu menjadi role model dalam membangun dan menerapkan budaya transfer pengetahuan dalam departemen atau divisi yang dipimpin (eng)', 'managerial');
INSERT INTO question_pa VALUES ('11', 'synergized', 'culture', 'SYNERGIZED TEAM', 'SYNERGIZED TEAM', 'Mampu menyusun strategi komunikasi, termasuk bahasa non verbal, sehingga mendukung implementasi dan pencapaian  strategi kerja bersama', 'Mampu menyusun strategi komunikasi, termasuk bahasa non verbal, sehingga mendukung implementasi dan pencapaian  strategi kerja bersama (eng)', 'managerial');
INSERT INTO question_pa VALUES ('12', 'synergized', 'culture', 'SYNERGIZED TEAM', 'SYNERGIZED TEAM', 'Mampu memberikan apresiasi seperti reward, recognition atas kualitas kerja timnya', 'Mampu memberikan apresiasi seperti reward, recognition atas kualitas kerja timnya (eng)', 'managerial');
INSERT INTO question_pa VALUES ('13', 'integrity', 'culture', 'INTEGRITY FOR ALL ACTION', 'INTEGRITY FOR ALL ACTION', 'Mampu bertindak secara konsisten dengan nilai-nilai dan prinsip-prinsip etika', 'Mampu bertindak secara konsisten dengan nilai-nilai dan prinsip-prinsip etika (eng)', 'nonstaff');
INSERT INTO question_pa VALUES ('14', 'integrity', 'culture', 'INTEGRITY FOR ALL ACTION', 'INTEGRITY FOR ALL ACTION', 'Mampu mempertahankan komitmen dan disiplin terhadap peraturan dan norma Perusahaan', 'Mampu mempertahankan komitmen dan disiplin terhadap peraturan dan norma Perusahaan (eng)', 'nonstaff');
INSERT INTO question_pa VALUES ('15', 'integrity', 'culture', 'INTEGRITY FOR ALL ACTION', 'INTEGRITY FOR ALL ACTION', 'Mampu menempatkan kepentingan Perusahaan di atas kepentingan pribadi', 'Mampu menempatkan kepentingan Perusahaan di atas kepentingan pribadi (eng)', 'nonstaff');
INSERT INTO question_pa VALUES ('16', 'integrity', 'culture', 'INTEGRITY FOR ALL ACTION', 'INTEGRITY FOR ALL ACTION', 'Mampu bertindak secara konsisten dengan nilai-nilai dan prinsip-prinsip etika', 'Mampu bertindak secara konsisten dengan nilai-nilai dan prinsip-prinsip etika (eng)', 'staff');
INSERT INTO question_pa VALUES ('17', 'integrity', 'culture', 'INTEGRITY FOR ALL ACTION', 'INTEGRITY FOR ALL ACTION', 'Mampu mempertahankan komitmen dan disiplin terhadap peraturan dan norma Perusahaan', 'Mampu mempertahankan komitmen dan disiplin terhadap peraturan dan norma Perusahaan (eng)', 'staff');
INSERT INTO question_pa VALUES ('18', 'integrity', 'culture', 'INTEGRITY FOR ALL ACTION', 'INTEGRITY FOR ALL ACTION', 'Mampu menempatkan kepentingan Perusahaan di atas kepentingan pribadi', 'Mampu menempatkan kepentingan Perusahaan di atas kepentingan pribadi (eng)', 'staff');
INSERT INTO question_pa VALUES ('19', 'integrity', 'culture', 'INTEGRITY FOR ALL ACTION', 'INTEGRITY FOR ALL ACTION', 'Mampu mengajak orang lain agar bertindak selaras dengan nilai-nilai dan prinsip-prinsip etika perusahaan dalam segala situasi dan kondisi', 'Mampu mengajak orang lain agar bertindak selaras dengan nilai-nilai dan prinsip-prinsip etika perusahaan dalam segala situasi dan kondisi (eng)', 'staffb');
INSERT INTO question_pa VALUES ('20', 'integrity', 'culture', 'INTEGRITY FOR ALL ACTION', 'INTEGRITY FOR ALL ACTION', 'Mampu menerapkan norma-norma secara konsisten dan melakukan pemantauan atas penerapan sikap integritas dalam ruang lingkup kerjanya.', 'Mampu menerapkan norma-norma secara konsisten dan melakukan pemantauan atas penerapan sikap integritas dalam ruang lingkup kerjanya. (eng)', 'staffb');
INSERT INTO question_pa VALUES ('21', 'integrity', 'culture', 'INTEGRITY FOR ALL ACTION', 'INTEGRITY FOR ALL ACTION', 'Mampu melakukan koreksi atau mengambil tindakan atas penyimpangan kode etik ataupun nilai-nilai yang dilakukan oleh orang lain dalam tataran unit/section', 'Mampu melakukan koreksi atau mengambil tindakan atas penyimpangan kode etik ataupun nilai-nilai yang dilakukan oleh orang lain dalam tataran unit/section (eng)', 'staffb');
INSERT INTO question_pa VALUES ('22', 'integrity', 'culture', 'INTEGRITY FOR ALL ACTION', 'INTEGRITY FOR ALL ACTION', 'Mampu memberikan apresiasi atau mengambil tindakan koreksi kepada individu atau tim atas perilaku-perilaku yang berkaitan dengan nilai-nilai dan prinsip-prinsip etika perusahaan dalam tataran departemen/divisi', 'Mampu memberikan apresiasi atau mengambil tindakan koreksi kepada individu atau tim atas perilaku-perilaku yang berkaitan dengan nilai-nilai dan prinsip-prinsip etika perusahaan dalam tataran departemen/divisi (eng)', 'managerial');
INSERT INTO question_pa VALUES ('23', 'integrity', 'culture', 'INTEGRITY FOR ALL ACTION', 'INTEGRITY FOR ALL ACTION', 'Mampu menjadi role model dalam menciptakan sistem dan mekanisme kontrol pelaksanaan peraturan dan norma Perusahaan', 'Mampu menjadi role model dalam menciptakan sistem dan mekanisme kontrol pelaksanaan peraturan dan norma Perusahaan (eng)', 'managerial');
INSERT INTO question_pa VALUES ('24', 'integrity', 'culture', 'INTEGRITY FOR ALL ACTION', 'INTEGRITY FOR ALL ACTION', 'Mampu secara sistematis dan strategis menciptakan budaya kerja yang mencerminkan dan mengimplementasikan nilai - nilai integritas dan etika di perusahaan', 'Mampu secara sistematis dan strategis menciptakan budaya kerja yang mencerminkan dan mengimplementasikan nilai - nilai integritas dan etika di perusahaan (eng)', 'managerial');
INSERT INTO question_pa VALUES ('25', 'growth', 'culture', 'GROWTH FOR CO PROSPERITY', 'GROWTH FOR CO PROSPERITY', 'Mampu berperan aktif dalam menjaga harmonisasi tim dengan cara menghormati dan menghargai perbedaan pendapat antar rekan kerja serta berusaha memahami sudut pandang orang lain.', 'Mampu berperan aktif dalam menjaga harmonisasi tim dengan cara menghormati dan menghargai perbedaan pendapat antar rekan kerja serta berusaha memahami sudut pandang orang lain. (eng)', 'nonstaff');
INSERT INTO question_pa VALUES ('26', 'growth', 'culture', 'GROWTH FOR CO PROSPERITY', 'GROWTH FOR CO PROSPERITY', 'Mampu melaksanakan pekerjaan yang ada dengan cara-cara yang sesuai dengan prinsip \"menang bersama\".', 'Mampu melaksanakan pekerjaan yang ada dengan cara-cara yang sesuai dengan prinsip \"menang bersama\". (eng)', 'nonstaff');
INSERT INTO question_pa VALUES ('27', 'growth', 'culture', 'GROWTH FOR CO PROSPERITY', 'GROWTH FOR CO PROSPERITY', 'Memperlihatkan perilaku kerja yang berorientasi pada keberlangsungan jangka panjang perusahaan.', 'Memperlihatkan perilaku kerja yang berorientasi pada keberlangsungan jangka panjang perusahaan. (eng)', 'nonstaff');
INSERT INTO question_pa VALUES ('28', 'growth', 'culture', 'GROWTH FOR CO PROSPERITY', 'GROWTH FOR CO PROSPERITY', 'Mampu berperan aktif dalam menjaga harmonisasi tim dengan cara menghormati dan menghargai perbedaan pendapat antar rekan kerja serta berusaha memahami sudut pandang orang lain.', 'Mampu berperan aktif dalam menjaga harmonisasi tim dengan cara menghormati dan menghargai perbedaan pendapat antar rekan kerja serta berusaha memahami sudut pandang orang lain. (eng)', 'staff');
INSERT INTO question_pa VALUES ('29', 'growth', 'culture', 'GROWTH FOR CO PROSPERITY', 'GROWTH FOR CO PROSPERITY', 'Mampu melaksanakan pekerjaan yang ada dengan cara-cara yang sesuai dengan prinsip \"menang bersama\".', 'Mampu melaksanakan pekerjaan yang ada dengan cara-cara yang sesuai dengan prinsip \"menang bersama\". (eng)', 'staff');
INSERT INTO question_pa VALUES ('30', 'growth', 'culture', 'GROWTH FOR CO PROSPERITY', 'GROWTH FOR CO PROSPERITY', 'Memperlihatkan perilaku kerja yang berorientasi pada keberlangsungan jangka panjang perusahaan.', 'Memperlihatkan perilaku kerja yang berorientasi pada keberlangsungan jangka panjang perusahaan. (eng)', 'staff');
INSERT INTO question_pa VALUES ('31', 'growth', 'culture', 'GROWTH FOR CO PROSPERITY', 'GROWTH FOR CO PROSPERITY', 'Mampu menjembatani perbedaan pendapat serta mengelola konflik-konflik yang terjadi dalam tim sehingga harmoni tim tetap terjaga.', 'Mampu menjembatani perbedaan pendapat serta mengelola konflik-konflik yang terjadi dalam tim sehingga harmoni tim tetap terjaga. (eng)', 'staffb');
INSERT INTO question_pa VALUES ('32', 'growth', 'culture', 'GROWTH FOR CO PROSPERITY', 'GROWTH FOR CO PROSPERITY', 'Mampu mengarahkan dan memastikan tim yang dipimpin senantiasa fokus pada keberhasilan dan kesejahteraan bersama', 'Mampu mengarahkan dan memastikan tim yang dipimpin senantiasa fokus pada keberhasilan dan kesejahteraan bersama (eng)', 'staffb');
INSERT INTO question_pa VALUES ('33', 'growth', 'culture', 'GROWTH FOR CO PROSPERITY', 'GROWTH FOR CO PROSPERITY', 'Mampu mengarahkan dan memastikan tim yang dipimpin memperlihatkan perilaku kerja yang berorientasi pada keberlangsungan jangka panjang bisnis perusahaan.', 'Mampu mengarahkan dan memastikan tim yang dipimpin memperlihatkan perilaku kerja yang berorientasi pada keberlangsungan jangka panjang bisnis perusahaan. (eng)', 'staffb');
INSERT INTO question_pa VALUES ('34', 'growth', 'culture', 'GROWTH FOR CO PROSPERITY', 'GROWTH FOR CO PROSPERITY', 'Mampu menjadi teladan dan role model dalam hal menjaga harmoni serta dorongan untuk bertumbuh dan sejahtera bersama baik dalam tim yang dipimpin maupun lintas department atau divisi.', 'Mampu menjadi teladan dan role model dalam hal menjaga harmoni serta dorongan untuk bertumbuh dan sejahtera bersama baik dalam tim yang dipimpin maupun lintas department atau divisi. (eng)', 'managerial');
INSERT INTO question_pa VALUES ('35', 'growth', 'culture', 'GROWTH FOR CO PROSPERITY', 'GROWTH FOR CO PROSPERITY', 'Mampu menginterpretasikan target dan rencana bisnis perusahaan menjadi target dan rencana kerja jangka menengah-panjang yang berorientasi pada keberlangsungan jangka panjang bisnis perusahaan.', 'Mampu menginterpretasikan target dan rencana bisnis perusahaan menjadi target dan rencana kerja jangka menengah-panjang yang berorientasi pada keberlangsungan jangka panjang bisnis perusahaan. (eng)', 'managerial');
INSERT INTO question_pa VALUES ('36', 'growth', 'culture', 'GROWTH FOR CO PROSPERITY', 'GROWTH FOR CO PROSPERITY', 'Mampu membangun budaya kerja dalam tim yang dipimpin yang mengutamakan keberhasilan dan kesejahteraan bersama bagi seluruh perusahaan beserta para stakeholder-nya serta secara konsisten fokus pada keberlangsungan jangka panjang bisnis perusahaan.', 'Mampu membangun budaya kerja dalam tim yang dipimpin yang mengutamakan keberhasilan dan kesejahteraan bersama bagi seluruh perusahaan beserta para stakeholder-nya serta secara konsisten fokus pada keberlangsungan jangka panjang bisnis perusahaan. (eng)', 'managerial');
INSERT INTO question_pa VALUES ('37', 'adaptive', 'culture', 'ADAPTIVE TO CHANGE', 'ADAPTIVE TO CHANGE', 'Mampu mengikuti perubahan berdasarkan bimbingan atau arahan dari atasan', 'Mampu mengikuti perubahan berdasarkan bimbingan atau arahan dari atasan (eng)', 'nonstaff');
INSERT INTO question_pa VALUES ('38', 'adaptive', 'culture', 'ADAPTIVE TO CHANGE', 'ADAPTIVE TO CHANGE', 'Mampu menyesuaikan diri dalam menghadapi perubahan di tempat kerja', 'Mampu menyesuaikan diri dalam menghadapi perubahan di tempat kerja (eng)', 'nonstaff');
INSERT INTO question_pa VALUES ('39', 'adaptive', 'culture', 'ADAPTIVE TO CHANGE', 'ADAPTIVE TO CHANGE', 'Mampu menyesuaikan cara kerja dengan menerapkan metode/proses yang selaras dengan ketentuan yang berlaku tanpa adanya arahan dari orang lain.', 'Mampu menyesuaikan cara kerja dengan menerapkan metode/proses yang selaras dengan ketentuan yang berlaku tanpa adanya arahan dari orang lain. (eng)', 'nonstaff');
INSERT INTO question_pa VALUES ('40', 'adaptive', 'culture', 'ADAPTIVE TO CHANGE', 'ADAPTIVE TO CHANGE', 'Secara proaktif mampu membantu orang lain dalam melakukan perubahan', 'Secara proaktif mampu membantu orang lain dalam melakukan perubahan (eng)', 'staff');
INSERT INTO question_pa VALUES ('41', 'adaptive', 'culture', 'ADAPTIVE TO CHANGE', 'ADAPTIVE TO CHANGE', 'Mampu mengembangkan kemampuan diri dalam menghadapi perubahan', 'Mampu mengembangkan kemampuan diri dalam menghadapi perubahan (eng)', 'staff');
INSERT INTO question_pa VALUES ('42', 'adaptive', 'culture', 'ADAPTIVE TO CHANGE', 'ADAPTIVE TO CHANGE', 'Mampu menyesuaikan prioritas kerja sesuai situasi di lapangan', 'Mampu menyesuaikan prioritas kerja sesuai situasi di lapangan (eng)', 'staff');
INSERT INTO question_pa VALUES ('43', 'adaptive', 'culture', 'ADAPTIVE TO CHANGE', 'ADAPTIVE TO CHANGE', 'Mampu menghadapi perubahan jangka pendek - menengah (1-2 tahun)  dengan cara melakukan inovasi praktis, melihat peluang dan cara baru dalam melaksanakan pekerjaannya', 'Mampu menghadapi perubahan jangka pendek - menengah (1-2 tahun)  dengan cara melakukan inovasi praktis, melihat peluang dan cara baru dalam melaksanakan pekerjaannya (eng)', 'staffb');
INSERT INTO question_pa VALUES ('44', 'adaptive', 'culture', 'ADAPTIVE TO CHANGE', 'ADAPTIVE TO CHANGE', 'Mampu memberikan arahan dan bimbingan untuk menghadapi perubahan yang terjadi serta mensosialisasikan arahan terkait perubahan yang dibutuhkan orang lain dan rekan kerja', 'Mampu memberikan arahan dan bimbingan untuk menghadapi perubahan yang terjadi serta mensosialisasikan arahan terkait perubahan yang dibutuhkan orang lain dan rekan kerja (eng)', 'staffb');
INSERT INTO question_pa VALUES ('45', 'adaptive', 'culture', 'ADAPTIVE TO CHANGE', 'ADAPTIVE TO CHANGE', 'Mampu menyelaraskan sumber daya  yang ada sehubungan dengan inovasi atau perubahan yang terjadi', 'Mampu menyelaraskan sumber daya  yang ada sehubungan dengan inovasi atau perubahan yang terjadi (eng)', 'staffb');
INSERT INTO question_pa VALUES ('46', 'adaptive', 'culture', 'ADAPTIVE TO CHANGE', 'ADAPTIVE TO CHANGE', 'Mampu mengantisipasi perubahan-perubahan yang perlu dilakukan dalam rangka mengimplementasikan strategi manajemen perusahaan jangka menengah-panjang', 'Mampu mengantisipasi perubahan-perubahan yang perlu dilakukan dalam rangka mengimplementasikan strategi manajemen perusahaan jangka menengah-panjang (eng)', 'managerial');
INSERT INTO question_pa VALUES ('47', 'adaptive', 'culture', 'ADAPTIVE TO CHANGE', 'ADAPTIVE TO CHANGE', 'Mampu menyusun sistematika perubahan yang mempertimbangkan akan dihadapi oleh departemen atau divisi dan mempertimbangkan efektivitas inovasi.', 'Mampu menyusun sistematika perubahan yang mempertimbangkan akan dihadapi oleh departemen atau divisi dan mempertimbangkan efektivitas inovasi. (eng)', 'managerial');
INSERT INTO question_pa VALUES ('48', 'adaptive', 'culture', 'ADAPTIVE TO CHANGE', 'ADAPTIVE TO CHANGE', 'Mampu mengantisipasi kebutuhan sumber daya yang akan diperlukan dalam rangka menyesuaikan dengan perubahan yang dihadapi (alokasi dana serta atau strategi yang akan dilakukan)', 'Mampu mengantisipasi kebutuhan sumber daya yang akan diperlukan dalam rangka menyesuaikan dengan perubahan yang dihadapi (alokasi dana serta atau strategi yang akan dilakukan) (eng)', 'managerial');
INSERT INTO question_pa VALUES ('49', 'passion', 'culture', 'PASSION FOR EXCELLENCE', 'PASSION FOR EXCELLENCE', 'Mampu mengintrospeksi diri dalam upaya mengidentifikasi kelebihan dan kekurangan dirinya serta melakukan usaha yang efektif untuk mengembangkan diri.', 'Mampu mengintrospeksi diri dalam upaya mengidentifikasi kelebihan dan kekurangan dirinya serta melakukan usaha yang efektif untuk mengembangkan diri. (eng)', 'nonstaff');
INSERT INTO question_pa VALUES ('50', 'passion', 'culture', 'PASSION FOR EXCELLENCE', 'PASSION FOR EXCELLENCE', 'Mampu memeriksa hasil kerja secara mandiri.', 'Mampu memeriksa hasil kerja secara mandiri. (eng)', 'nonstaff');
INSERT INTO question_pa VALUES ('51', 'passion', 'culture', 'PASSION FOR EXCELLENCE', 'PASSION FOR EXCELLENCE', 'Secara konsisten memberikan usaha yang terbaik dalam melaksanakan seluruh tugas yang diberikan.', 'Secara konsisten memberikan usaha yang terbaik dalam melaksanakan seluruh tugas yang diberikan. (eng)', 'nonstaff');
INSERT INTO question_pa VALUES ('52', 'passion', 'culture', 'PASSION FOR EXCELLENCE', 'PASSION FOR EXCELLENCE', 'Secara proaktif mampu meminta umpan balik dari orang lain terkait hasil kerja dan kekurangan dirinya dalam rangka mengembangkan diri di masa yang akan datang.', 'Secara proaktif mampu meminta umpan balik dari orang lain terkait hasil kerja dan kekurangan dirinya dalam rangka mengembangkan diri di masa yang akan datang. (eng)', 'staff');
INSERT INTO question_pa VALUES ('53', 'passion', 'culture', 'PASSION FOR EXCELLENCE', 'PASSION FOR EXCELLENCE', 'Mampu mengelola dan menginternalisasikan umpan balik dari orang lain serta belajar dari kesalahan diri sendiri maupun orang lain dalam rangka meningkatkan hasil kerja atau pengembangan diri', 'Mampu mengelola dan menginternalisasikan umpan balik dari orang lain serta belajar dari kesalahan diri sendiri maupun orang lain dalam rangka meningkatkan hasil kerja atau pengembangan diri (eng)', 'staff');
INSERT INTO question_pa VALUES ('54', 'passion', 'culture', 'PASSION FOR EXCELLENCE', 'PASSION FOR EXCELLENCE', 'Mampu mempengaruhi rekan-rekan kerja-nya untuk memberikan usaha terbaik ketika menyelesaikan tugas-tugas yang ada', 'Mampu mempengaruhi rekan-rekan kerja-nya untuk memberikan usaha terbaik ketika menyelesaikan tugas-tugas yang ada (eng)', 'staff');
INSERT INTO question_pa VALUES ('55', 'passion', 'culture', 'PASSION FOR EXCELLENCE', 'PASSION FOR EXCELLENCE', 'Secara konsisten mampu mendorong dan mengarahkan anggota tim yang dipimpin untuk memberikan usaha terbaik dan mencapai hasil kerja yang unggul dan melebihi ekspektasi.', 'Secara konsisten mampu mendorong dan mengarahkan anggota tim yang dipimpin untuk memberikan usaha terbaik dan mencapai hasil kerja yang unggul dan melebihi ekspektasi. (eng)', 'staffb');
INSERT INTO question_pa VALUES ('56', 'passion', 'culture', 'PASSION FOR EXCELLENCE', 'PASSION FOR EXCELLENCE', 'Mampu mendorong anggota tim untuk selalu mencari dan menemukan cara-cara baru dan terbaik dalam melakukan pekerjaan-nya masing-masing.', 'Mampu mendorong anggota tim untuk selalu mencari dan menemukan cara-cara baru dan terbaik dalam melakukan pekerjaan-nya masing-masing. (eng)', 'staffb');
INSERT INTO question_pa VALUES ('57', 'passion', 'culture', 'PASSION FOR EXCELLENCE', 'PASSION FOR EXCELLENCE', 'Mampu memberikan umpan balik yang konstruktif dan berkualitas bagi rekan kerja atau tim yang dipimpin dalam rangka menemukan cara terbaik untuk meningkatkan kualias kerja dan mencapai hasil kerja yang melebihi ekspektasi.', 'Mampu memberikan umpan balik yang konstruktif dan berkualitas bagi rekan kerja atau tim yang dipimpin dalam rangka menemukan cara terbaik untuk meningkatkan kualias kerja dan mencapai hasil kerja yang melebihi ekspektasi. (eng)', 'staffb');
INSERT INTO question_pa VALUES ('58', 'passion', 'culture', 'PASSION FOR EXCELLENCE', 'PASSION FOR EXCELLENCE', 'Mampu menjadi teladan dan role model dalam hal menentukan dan mengejar standar tinggi dan keunggulan dalam melaksanakan tugas-tugas serta melewati batasan-batasan yang ada saat ini.', 'Mampu menjadi teladan dan role model dalam hal menentukan dan mengejar standar tinggi dan keunggulan dalam melaksanakan tugas-tugas serta melewati batasan-batasan yang ada saat ini. (eng)', 'managerial');
INSERT INTO question_pa VALUES ('59', 'passion', 'culture', 'PASSION FOR EXCELLENCE', 'PASSION FOR EXCELLENCE', 'Secara konsisten mampu mendorong dan mengarahkan anggota tim untuk memberikan usaha dan hasil kerja yang melebihi ekspektasi.', 'Secara konsisten mampu mendorong dan mengarahkan anggota tim untuk memberikan usaha dan hasil kerja yang melebihi ekspektasi. (eng)', 'managerial');
INSERT INTO question_pa VALUES ('60', 'passion', 'culture', 'PASSION FOR EXCELLENCE', 'PASSION FOR EXCELLENCE', 'Mampu menciptakan budaya kerja dalam tim yg dipimpin yang selalu memberikan usaha terbaik, secara konsisten berusaha mencari cara terbaik untuk meningkatkan kualitas kerja serta mengutamakan hasil kerja yang melebihi ekspektasi.', 'Mampu menciptakan budaya kerja dalam tim yg dipimpin yang selalu memberikan usaha terbaik, secara konsisten berusaha mencari cara terbaik untuk meningkatkan kualitas kerja serta mengutamakan hasil kerja yang melebihi ekspektasi. (eng)', 'managerial');
INSERT INTO question_pa VALUES ('61', 'leadership', 'leadership', 'Manage & Planning', 'Manage & Planning', 'Menunjukkan kemampuan time management dengan cara menyusun prioritas dalam rangka menyelesaikan tugas-tugas yang ada, mengarahkan dan memastikan anggota tim bekerja sesuai dengan prioritas yang telah disusun serta mampu menyusun sistem dan mekanisme kontrol sehingga secara simultan mampu menyelesaikan pekerjaan-pekerjaan yang ada tepat waktu dengan hasil sesuai harapan.', 'Menunjukkan kemampuan time management dengan cara menyusun prioritas dalam rangka menyelesaikan tugas-tugas yang ada, mengarahkan dan memastikan anggota tim bekerja sesuai dengan prioritas yang telah disusun serta mampu menyusun sistem dan mekanisme kontrol sehingga secara simultan mampu menyelesaikan pekerjaan-pekerjaan yang ada tepat waktu dengan hasil sesuai harapan. (eng)', 'staffb');
INSERT INTO question_pa VALUES ('62', 'leadership', 'leadership', 'Manage & Planning', 'Manage & Planning', 'Mampu menyusun rencana kerja jangka pendek-menengah dengan target yang jelas, terukur dan obyektif untuk tim yang dipimpin serta mampu mengusulkan kebutuhan sumber daya yang diperlukan untuk mengimplementasikan rencana kerja tersebut.', 'Mampu menyusun rencana kerja jangka pendek-menengah dengan target yang jelas, terukur dan obyektif untuk tim yang dipimpin serta mampu mengusulkan kebutuhan sumber daya yang diperlukan untuk mengimplementasikan rencana kerja tersebut. (eng)', 'staffb');
INSERT INTO question_pa VALUES ('63', 'leadership', 'leadership', 'Manage & Planning', 'Manage & Planning', 'Mampu menginterpretasikan rencana bisnis perusahaan menjadi rencana kerja dan target jangka menengah-panjang untuk tim yang dipimpin serta mampu menentukan & memutuskan sumber daya yang diperlukan untuk mengimplementasikan rencana kerja tersebut.', 'Mampu menginterpretasikan rencana bisnis perusahaan menjadi rencana kerja dan target jangka menengah-panjang untuk tim yang dipimpin serta mampu menentukan & memutuskan sumber daya yang diperlukan untuk mengimplementasikan rencana kerja tersebut. (eng)', 'managerial');
INSERT INTO question_pa VALUES ('64', 'leadership', 'leadership', 'Manage & Planning', 'Manage & Planning', 'Mampu memprediksi dan mengidentifikasi berbagai hambatan dan tantangan yang mungkin terjadi di masa yang akan datang serta menyesuaikan dan mengoptimalisasi sumber daya yang ada sehingga secara efektif dan efisien mampu menangani berbagai proyek yang kompleks secara paralel dengan penyelesaian tepat waktu dan hasil sesuai ekspektasi manajemen.', 'Mampu memprediksi dan mengidentifikasi berbagai hambatan dan tantangan yang mungkin terjadi di masa yang akan datang serta menyesuaikan dan mengoptimalisasi sumber daya yang ada sehingga secara efektif dan efisien mampu menangani berbagai proyek yang kompleks secara paralel dengan penyelesaian tepat waktu dan hasil sesuai ekspektasi manajemen. (eng)', 'managerial');
INSERT INTO question_pa VALUES ('65', 'leadership', 'leadership', 'Decision Making', 'Decision Making', 'Mampu melihat dan menganalisa masalah dan isu jangka pendek-menengah dari berbagai sudut pandang dalam proses pengambilan keputusan di ruang lingkup kerjanya serta mampu mengambil keputusan dengan dampak jangka pendek-menengah dengan menggunakan proyeksi untung rugi dan mempertimbangkan faktor efisiensi dalam proses pengambilan keputusan.', 'Mampu melihat dan menganalisa masalah dan isu jangka pendek-menengah dari berbagai sudut pandang dalam proses pengambilan keputusan di ruang lingkup kerjanya serta mampu mengambil keputusan dengan dampak jangka pendek-menengah dengan menggunakan proyeksi untung rugi dan mempertimbangkan faktor efisiensi dalam proses pengambilan keputusan. (eng)', 'staffb');
INSERT INTO question_pa VALUES ('66', 'leadership', 'leadership', 'Decision Making', 'Decision Making', 'Mampu menciptakan keterlibatan tim atau pihak-pihak terkait di dalam proses pengambilan dan pelaksanaan keputusan dalam section/department yg dipimpin.', 'Mampu menciptakan keterlibatan tim atau pihak-pihak terkait di dalam proses pengambilan dan pelaksanaan keputusan dalam section/department yg dipimpin. (eng)', 'staffb');
INSERT INTO question_pa VALUES ('67', 'leadership', 'leadership', 'Decision Making', 'Decision Making', 'Mampu melihat dan menganalisa isu strategis jangka menengah-panjang dari berbagai sudut pandang serta mampu mengambil keputusan dengan dampak jangka menengah-panjang bagi perusahaan berdasarkan hasil analisa yang mendalam dan menyeluruh.', 'Mampu melihat dan menganalisa isu strategis jangka menengah-panjang dari berbagai sudut pandang serta mampu mengambil keputusan dengan dampak jangka menengah-panjang bagi perusahaan berdasarkan hasil analisa yang mendalam dan menyeluruh. (eng)', 'managerial');
INSERT INTO question_pa VALUES ('68', 'leadership', 'leadership', 'Decision Making', 'Decision Making', 'Mampu membangun budaya di mana setiap anggota tim mau berpartisipasi dan terlibat dalam proses pengambilan keputusan tertentu dalam department/divisi yang dipimpin.', 'Mampu membangun budaya di mana setiap anggota tim mau berpartisipasi dan terlibat dalam proses pengambilan keputusan tertentu dalam department/divisi yang dipimpin. (eng)', 'managerial');
INSERT INTO question_pa VALUES ('69', 'leadership', 'leadership', 'Developing Others', 'Developing Others', 'Mampu mengidentifikasi kekuatan dan kelemahan anggota tim serta menyesuaikan support yang diberikan kepada anggota tim.', 'Mampu mengidentifikasi kekuatan dan kelemahan anggota tim serta menyesuaikan support yang diberikan kepada anggota tim. (eng)', 'staffb');
INSERT INTO question_pa VALUES ('70', 'leadership', 'leadership', 'Developing Others', 'Developing Others', 'Secara proaktif menggunakan kesempatan yang ada untuk membangun pertumbuhan anggota tim serta secara regular memberikan umpan balik yang membangun dan saran pengembangan diri yang dapat dilaksanakan oleh seluruh anggota tim.', 'Secara proaktif menggunakan kesempatan yang ada untuk membangun pertumbuhan anggota tim serta secara regular memberikan umpan balik yang membangun dan saran pengembangan diri yang dapat dilaksanakan oleh seluruh anggota tim. (eng)', 'staffb');
INSERT INTO question_pa VALUES ('71', 'leadership', 'leadership', 'Developing Others', 'Developing Others', 'Mampu memimpin dengan cara menunjukkan teladan dan dipandang sebagai seorang mentor dan role model yg baik bagi anggota tim.', 'Mampu memimpin dengan cara menunjukkan teladan dan dipandang sebagai seorang mentor dan role model yg baik bagi anggota tim. (eng)', 'managerial');
INSERT INTO question_pa VALUES ('72', 'leadership', 'leadership', 'Developing Others', 'Developing Others', 'Secara konsisten memberikan umpan balik, bimbingan, arahan dan support yang berkualitas bagi anggota tim dan mampu menyusun rencana pengembangan bagi anggota tim-nya dengan mempertimbangkan kekuatan dan kelemahan tiap individu serta mengimplementasikan dan memantau pelaksanaan rencana pengembangan tersebut sehingga dapat memaksimalkan potensi setiap anggota tim.', 'Secara konsisten memberikan umpan balik, bimbingan, arahan dan support yang berkualitas bagi anggota tim dan mampu menyusun rencana pengembangan bagi anggota tim-nya dengan mempertimbangkan kekuatan dan kelemahan tiap individu serta mengimplementasikan dan memantau pelaksanaan rencana pengembangan tersebut sehingga dapat memaksimalkan potensi setiap anggota tim. (eng)', 'managerial');
