-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.4.24-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.3.0.6589
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table pa_2023.transaksi_2023
CREATE TABLE IF NOT EXISTS `transaksi_2023` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idkar` bigint(20) NOT NULL,
  `fortable` varchar(20) COLLATE latin1_general_ci NOT NULL,
  `value_1` text COLLATE latin1_general_ci NOT NULL,
  `score_1` int(1) NOT NULL DEFAULT 0,
  `value_2` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_2` int(1) DEFAULT NULL,
  `value_3` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_3` int(1) DEFAULT NULL,
  `value_4` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_4` int(1) DEFAULT NULL,
  `value_5` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_5` int(1) DEFAULT NULL,
  `total_score` decimal(4,2) DEFAULT NULL,
  `synergized1` int(1) DEFAULT NULL,
  `synergized2` int(1) DEFAULT NULL,
  `synergized3` int(1) DEFAULT NULL,
  `integrity1` int(1) DEFAULT NULL,
  `integrity2` int(1) DEFAULT NULL,
  `integrity3` int(1) DEFAULT NULL,
  `growth1` int(1) DEFAULT NULL,
  `growth2` int(1) DEFAULT NULL,
  `growth3` int(1) DEFAULT NULL,
  `adaptive1` int(1) DEFAULT NULL,
  `adaptive2` int(1) DEFAULT NULL,
  `adaptive3` int(1) DEFAULT NULL,
  `passion1` int(1) DEFAULT NULL,
  `passion2` int(1) DEFAULT NULL,
  `passion3` int(1) DEFAULT NULL,
  `leadership1` int(1) DEFAULT NULL,
  `leadership2` int(1) DEFAULT NULL,
  `leadership3` int(1) DEFAULT NULL,
  `leadership4` int(1) DEFAULT NULL,
  `leadership5` int(1) DEFAULT NULL,
  `leadership6` int(1) DEFAULT NULL,
  `created_by` bigint(20) NOT NULL,
  `created_date` datetime NOT NULL,
  `updated_by` bigint(20) DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `periode` varchar(4) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `comment_a1` text COLLATE latin1_general_ci DEFAULT NULL,
  `comment_a2` text COLLATE latin1_general_ci DEFAULT NULL,
  `comment_a3` text COLLATE latin1_general_ci DEFAULT NULL,
  `total_culture` decimal(4,2) DEFAULT 0.00,
  `total_leadership` decimal(4,2) DEFAULT 0.00,
  `rating_a1` decimal(4,2) DEFAULT NULL,
  `rating_a2` decimal(4,2) DEFAULT NULL,
  `rating_a3` decimal(4,2) DEFAULT NULL,
  `promotion` enum('Y','N') COLLATE latin1_general_ci NOT NULL DEFAULT 'N',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table pa_2023.transaksi_2023: ~3 rows (approximately)
REPLACE INTO `transaksi_2023` (`id`, `idkar`, `fortable`, `value_1`, `score_1`, `value_2`, `score_2`, `value_3`, `score_3`, `value_4`, `score_4`, `value_5`, `score_5`, `total_score`, `synergized1`, `synergized2`, `synergized3`, `integrity1`, `integrity2`, `integrity3`, `growth1`, `growth2`, `growth3`, `adaptive1`, `adaptive2`, `adaptive3`, `passion1`, `passion2`, `passion3`, `leadership1`, `leadership2`, `leadership3`, `leadership4`, `leadership5`, `leadership6`, `created_by`, `created_date`, `updated_by`, `updated_date`, `periode`, `comment_a1`, `comment_a2`, `comment_a3`, `total_culture`, `total_leadership`, `rating_a1`, `rating_a2`, `rating_a3`, `promotion`) VALUES
	(1, 3351, '', 'a', 5, '', 0, '', 0, '', 0, '', 0, 5.00, 4, 5, 4, 5, 4, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 0, 3351, '2023-10-16 16:15:03', 50914, '2023-10-16 18:01:22', '2023', 'oke', 'ok deh', NULL, 4.73, 4.80, 5.00, 4.00, NULL, 'N'),
	(2, 51321, 'managerial', 'objective 1', 4, 'objective 2', 5, '', 0, '', 0, '', 0, 4.50, 5, 4, 5, 5, 4, 5, 4, 4, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 51321, '2023-10-17 11:36:34', 6242, '2023-10-17 14:10:31', '2023', 'oke', 'okay', 'oke aja deh', 4.73, 4.33, 5.00, 4.00, 4.00, 'N'),
	(3, 4491, 'staff', 'HCIS', 5, 'Darwinbox', 5, '', 0, '', 0, '', 0, 5.00, 2, 4, 5, 4, 5, 5, 5, 5, 4, 5, 5, 4, 5, 3, 4, 0, 0, 0, 0, 0, 0, 4491, '2023-10-17 14:17:05', 44051, '2023-10-17 14:25:56', '2023', 'oke good', 'MPP not available', NULL, 4.33, 0.00, 4.00, 0.00, NULL, 'N');

-- Dumping structure for table pa_2023.transaksi_2023_a1
CREATE TABLE IF NOT EXISTS `transaksi_2023_a1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idkar` bigint(20) NOT NULL,
  `fortable` varchar(20) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `value_1` text COLLATE latin1_general_ci NOT NULL,
  `score_1` int(1) NOT NULL DEFAULT 0,
  `value_2` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_2` int(1) DEFAULT NULL,
  `value_3` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_3` int(1) DEFAULT NULL,
  `value_4` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_4` int(1) DEFAULT NULL,
  `value_5` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_5` int(1) DEFAULT NULL,
  `total_score` decimal(4,2) DEFAULT NULL,
  `synergized1` int(1) DEFAULT NULL,
  `synergized2` int(1) DEFAULT NULL,
  `synergized3` int(1) DEFAULT NULL,
  `integrity1` int(1) DEFAULT NULL,
  `integrity2` int(1) DEFAULT NULL,
  `integrity3` int(1) DEFAULT NULL,
  `growth1` int(1) DEFAULT NULL,
  `growth2` int(1) DEFAULT NULL,
  `growth3` int(1) DEFAULT NULL,
  `adaptive1` int(1) DEFAULT NULL,
  `adaptive2` int(1) DEFAULT NULL,
  `adaptive3` int(1) DEFAULT NULL,
  `passion1` int(1) DEFAULT NULL,
  `passion2` int(1) DEFAULT NULL,
  `passion3` int(1) DEFAULT NULL,
  `leadership1` int(1) DEFAULT NULL,
  `leadership2` int(1) DEFAULT NULL,
  `leadership3` int(1) DEFAULT NULL,
  `leadership4` int(1) DEFAULT NULL,
  `leadership5` int(1) DEFAULT NULL,
  `leadership6` int(1) DEFAULT NULL,
  `created_by` bigint(20) NOT NULL,
  `created_date` datetime NOT NULL,
  `updated_by` bigint(20) DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `periode` varchar(4) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `comment_a1` text COLLATE latin1_general_ci DEFAULT NULL,
  `comment_a2` text COLLATE latin1_general_ci DEFAULT NULL,
  `comment_a3` text COLLATE latin1_general_ci DEFAULT NULL,
  `total_culture` decimal(4,2) DEFAULT 0.00,
  `total_leadership` decimal(4,2) DEFAULT 0.00,
  `rating_a1` decimal(4,2) DEFAULT NULL,
  `rating_a2` decimal(4,2) DEFAULT NULL,
  `rating_a3` decimal(4,2) DEFAULT NULL,
  `promotion` enum('Y','N') COLLATE latin1_general_ci NOT NULL DEFAULT 'N',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table pa_2023.transaksi_2023_a1: ~2 rows (approximately)
REPLACE INTO `transaksi_2023_a1` (`id`, `idkar`, `fortable`, `value_1`, `score_1`, `value_2`, `score_2`, `value_3`, `score_3`, `value_4`, `score_4`, `value_5`, `score_5`, `total_score`, `synergized1`, `synergized2`, `synergized3`, `integrity1`, `integrity2`, `integrity3`, `growth1`, `growth2`, `growth3`, `adaptive1`, `adaptive2`, `adaptive3`, `passion1`, `passion2`, `passion3`, `leadership1`, `leadership2`, `leadership3`, `leadership4`, `leadership5`, `leadership6`, `created_by`, `created_date`, `updated_by`, `updated_date`, `periode`, `comment_a1`, `comment_a2`, `comment_a3`, `total_culture`, `total_leadership`, `rating_a1`, `rating_a2`, `rating_a3`, `promotion`) VALUES
	(1, 3351, '', 'a', 5, '', 0, '', 0, '', 0, '', 0, 5.00, 4, 5, 4, 5, 4, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 0, 44051, '2023-10-16 17:55:33', NULL, NULL, '2023', 'oke', NULL, NULL, 4.73, 4.80, 5.00, NULL, NULL, 'N'),
	(2, 51321, 'managerial', 'objective 1', 4, 'objective 2', 5, '', 0, '', 0, '', 0, 4.50, 5, 4, 5, 5, 4, 5, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 4, 4, 4, 44051, '2023-10-17 13:43:20', NULL, NULL, '2023', 'oke', NULL, NULL, 4.73, 4.33, 5.00, NULL, NULL, 'Y'),
	(3, 4491, 'staff', 'HCIS', 5, 'Darwinbox', 5, '', 0, '', 0, '', 0, 5.00, 2, 4, 5, 4, 5, 5, 5, 5, 4, 5, 5, 4, 5, 3, 4, 0, 0, 0, 0, 0, 0, 51321, '2023-10-17 14:19:21', NULL, NULL, '2023', 'oke good', NULL, NULL, 4.33, 0.00, 4.00, NULL, NULL, 'Y');

-- Dumping structure for table pa_2023.transaksi_2023_a2
CREATE TABLE IF NOT EXISTS `transaksi_2023_a2` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idkar` bigint(20) NOT NULL,
  `fortable` varchar(20) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `value_1` text COLLATE latin1_general_ci NOT NULL,
  `score_1` int(1) NOT NULL DEFAULT 0,
  `value_2` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_2` int(1) DEFAULT NULL,
  `value_3` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_3` int(1) DEFAULT NULL,
  `value_4` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_4` int(1) DEFAULT NULL,
  `value_5` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_5` int(1) DEFAULT NULL,
  `total_score` decimal(4,2) DEFAULT NULL,
  `synergized1` int(1) DEFAULT NULL,
  `synergized2` int(1) DEFAULT NULL,
  `synergized3` int(1) DEFAULT NULL,
  `integrity1` int(1) DEFAULT NULL,
  `integrity2` int(1) DEFAULT NULL,
  `integrity3` int(1) DEFAULT NULL,
  `growth1` int(1) DEFAULT NULL,
  `growth2` int(1) DEFAULT NULL,
  `growth3` int(1) DEFAULT NULL,
  `adaptive1` int(1) DEFAULT NULL,
  `adaptive2` int(1) DEFAULT NULL,
  `adaptive3` int(1) DEFAULT NULL,
  `passion1` int(1) DEFAULT NULL,
  `passion2` int(1) DEFAULT NULL,
  `passion3` int(1) DEFAULT NULL,
  `leadership1` int(1) DEFAULT NULL,
  `leadership2` int(1) DEFAULT NULL,
  `leadership3` int(1) DEFAULT NULL,
  `leadership4` int(1) DEFAULT NULL,
  `leadership5` int(1) DEFAULT NULL,
  `leadership6` int(1) DEFAULT NULL,
  `created_by` bigint(20) NOT NULL,
  `created_date` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `updated_by` bigint(20) DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `periode` varchar(4) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `comment_a1` text COLLATE latin1_general_ci DEFAULT NULL,
  `comment_a2` text COLLATE latin1_general_ci DEFAULT NULL,
  `comment_a3` text COLLATE latin1_general_ci DEFAULT NULL,
  `total_culture` decimal(4,2) DEFAULT NULL,
  `total_leadership` decimal(4,2) DEFAULT NULL,
  `rating_a1` decimal(4,2) DEFAULT NULL,
  `rating_a2` decimal(4,2) DEFAULT NULL,
  `rating_a3` decimal(4,2) DEFAULT NULL,
  `promotion` enum('Y','N') COLLATE latin1_general_ci NOT NULL DEFAULT 'N',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table pa_2023.transaksi_2023_a2: ~3 rows (approximately)
REPLACE INTO `transaksi_2023_a2` (`id`, `idkar`, `fortable`, `value_1`, `score_1`, `value_2`, `score_2`, `value_3`, `score_3`, `value_4`, `score_4`, `value_5`, `score_5`, `total_score`, `synergized1`, `synergized2`, `synergized3`, `integrity1`, `integrity2`, `integrity3`, `growth1`, `growth2`, `growth3`, `adaptive1`, `adaptive2`, `adaptive3`, `passion1`, `passion2`, `passion3`, `leadership1`, `leadership2`, `leadership3`, `leadership4`, `leadership5`, `leadership6`, `created_by`, `created_date`, `updated_by`, `updated_date`, `periode`, `comment_a1`, `comment_a2`, `comment_a3`, `total_culture`, `total_leadership`, `rating_a1`, `rating_a2`, `rating_a3`, `promotion`) VALUES
	(1, 3351, '', 'a', 5, '', 0, '', 0, '', 0, '', 0, 5.00, 4, 5, 4, 5, 4, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 0, 50914, '2023-10-16 11:01:22', NULL, NULL, '2023', NULL, 'ok deh', NULL, NULL, NULL, NULL, 4.00, NULL, 'N'),
	(2, 51321, 'managerial', 'objective 1', 4, 'objective 2', 5, '', 0, '', 0, '', 0, 4.50, 5, 4, 5, 5, 4, 5, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 4, 4, 4, 50914, '2023-10-17 07:04:05', NULL, NULL, '2023', NULL, 'okay', NULL, NULL, NULL, NULL, 4.00, NULL, 'N'),
	(3, 4491, 'staff', 'HCIS', 5, 'Darwinbox', 5, '', 0, '', 0, '', 0, 5.00, 2, 4, 5, 4, 5, 5, 5, 5, 4, 5, 5, 4, 5, 3, 4, 0, 0, 0, 0, 0, 0, 44051, '2023-10-17 07:25:56', NULL, NULL, '2023', NULL, 'MPP not available', NULL, NULL, NULL, NULL, 4.00, NULL, 'N');

-- Dumping structure for table pa_2023.transaksi_2023_a3
CREATE TABLE IF NOT EXISTS `transaksi_2023_a3` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idkar` bigint(20) NOT NULL,
  `fortable` varchar(20) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `value_1` text COLLATE latin1_general_ci NOT NULL,
  `score_1` int(1) NOT NULL DEFAULT 0,
  `value_2` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_2` int(1) DEFAULT NULL,
  `value_3` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_3` int(1) DEFAULT NULL,
  `value_4` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_4` int(1) DEFAULT NULL,
  `value_5` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_5` int(1) DEFAULT NULL,
  `total_score` decimal(4,2) DEFAULT NULL,
  `synergized1` int(1) DEFAULT NULL,
  `synergized2` int(1) DEFAULT NULL,
  `synergized3` int(1) DEFAULT NULL,
  `integrity1` int(1) DEFAULT NULL,
  `integrity2` int(1) DEFAULT NULL,
  `integrity3` int(1) DEFAULT NULL,
  `growth1` int(1) DEFAULT NULL,
  `growth2` int(1) DEFAULT NULL,
  `growth3` int(1) DEFAULT NULL,
  `adaptive1` int(1) DEFAULT NULL,
  `adaptive2` int(1) DEFAULT NULL,
  `adaptive3` int(1) DEFAULT NULL,
  `passion1` int(1) DEFAULT NULL,
  `passion2` int(1) DEFAULT NULL,
  `passion3` int(1) DEFAULT NULL,
  `leadership1` int(1) DEFAULT NULL,
  `leadership2` int(1) DEFAULT NULL,
  `leadership3` int(1) DEFAULT NULL,
  `leadership4` int(1) DEFAULT NULL,
  `leadership5` int(1) DEFAULT NULL,
  `leadership6` int(1) DEFAULT NULL,
  `created_by` bigint(20) NOT NULL,
  `created_date` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `updated_by` bigint(20) DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `periode` varchar(4) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `comment_a1` text COLLATE latin1_general_ci DEFAULT NULL,
  `comment_a2` text COLLATE latin1_general_ci DEFAULT NULL,
  `comment_a3` text COLLATE latin1_general_ci DEFAULT NULL,
  `total_culture` decimal(4,2) DEFAULT NULL,
  `total_leadership` decimal(4,2) DEFAULT NULL,
  `rating_a1` decimal(4,2) DEFAULT NULL,
  `rating_a2` decimal(4,2) DEFAULT NULL,
  `rating_a3` decimal(4,2) DEFAULT NULL,
  `promotion` enum('Y','N') COLLATE latin1_general_ci NOT NULL DEFAULT 'N',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table pa_2023.transaksi_2023_a3: ~1 rows (approximately)
REPLACE INTO `transaksi_2023_a3` (`id`, `idkar`, `fortable`, `value_1`, `score_1`, `value_2`, `score_2`, `value_3`, `score_3`, `value_4`, `score_4`, `value_5`, `score_5`, `total_score`, `synergized1`, `synergized2`, `synergized3`, `integrity1`, `integrity2`, `integrity3`, `growth1`, `growth2`, `growth3`, `adaptive1`, `adaptive2`, `adaptive3`, `passion1`, `passion2`, `passion3`, `leadership1`, `leadership2`, `leadership3`, `leadership4`, `leadership5`, `leadership6`, `created_by`, `created_date`, `updated_by`, `updated_date`, `periode`, `comment_a1`, `comment_a2`, `comment_a3`, `total_culture`, `total_leadership`, `rating_a1`, `rating_a2`, `rating_a3`, `promotion`) VALUES
	(1, 51321, 'managerial', 'objective 1', 4, 'objective 2', 5, '', 0, '', 0, '', 0, 4.50, 5, 4, 5, 5, 4, 5, 4, 4, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 6242, '2023-10-17 07:10:31', NULL, NULL, '2023', NULL, NULL, 'oke aja deh', NULL, NULL, NULL, NULL, 4.00, 'N');

-- Dumping structure for table pa_2023.transaksi_2023_awal
CREATE TABLE IF NOT EXISTS `transaksi_2023_awal` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idkar` bigint(20) NOT NULL,
  `fortable` varchar(20) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `value_1` text COLLATE latin1_general_ci NOT NULL,
  `score_1` int(1) NOT NULL DEFAULT 0,
  `value_2` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_2` int(1) DEFAULT NULL,
  `value_3` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_3` int(1) DEFAULT NULL,
  `value_4` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_4` int(1) DEFAULT NULL,
  `value_5` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_5` int(1) DEFAULT NULL,
  `total_score` decimal(4,2) DEFAULT NULL,
  `synergized1` int(1) DEFAULT NULL,
  `synergized2` int(1) DEFAULT NULL,
  `synergized3` int(1) DEFAULT NULL,
  `integrity1` int(1) DEFAULT NULL,
  `integrity2` int(1) DEFAULT NULL,
  `integrity3` int(1) DEFAULT NULL,
  `growth1` int(1) DEFAULT NULL,
  `growth2` int(1) DEFAULT NULL,
  `growth3` int(1) DEFAULT NULL,
  `adaptive1` int(1) DEFAULT NULL,
  `adaptive2` int(1) DEFAULT NULL,
  `adaptive3` int(1) DEFAULT NULL,
  `passion1` int(1) DEFAULT NULL,
  `passion2` int(1) DEFAULT NULL,
  `passion3` int(1) DEFAULT NULL,
  `leadership1` int(1) DEFAULT NULL,
  `leadership2` int(1) DEFAULT NULL,
  `leadership3` int(1) DEFAULT NULL,
  `leadership4` int(1) DEFAULT NULL,
  `leadership5` int(1) DEFAULT NULL,
  `leadership6` int(1) DEFAULT NULL,
  `created_by` bigint(20) NOT NULL,
  `created_date` datetime NOT NULL,
  `updated_by` bigint(20) DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `periode` varchar(4) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `comment_a1` text COLLATE latin1_general_ci DEFAULT NULL,
  `comment_a2` text COLLATE latin1_general_ci DEFAULT NULL,
  `comment_a3` text COLLATE latin1_general_ci DEFAULT NULL,
  `total_culture` decimal(4,2) DEFAULT 0.00,
  `total_leadership` decimal(4,2) DEFAULT 0.00,
  `rating_a1` decimal(4,2) DEFAULT NULL,
  `rating_a2` decimal(4,2) DEFAULT NULL,
  `rating_a3` decimal(4,2) DEFAULT NULL,
  `promotion` enum('Y','N') COLLATE latin1_general_ci NOT NULL DEFAULT 'N',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table pa_2023.transaksi_2023_awal: ~2 rows (approximately)
REPLACE INTO `transaksi_2023_awal` (`id`, `idkar`, `fortable`, `value_1`, `score_1`, `value_2`, `score_2`, `value_3`, `score_3`, `value_4`, `score_4`, `value_5`, `score_5`, `total_score`, `synergized1`, `synergized2`, `synergized3`, `integrity1`, `integrity2`, `integrity3`, `growth1`, `growth2`, `growth3`, `adaptive1`, `adaptive2`, `adaptive3`, `passion1`, `passion2`, `passion3`, `leadership1`, `leadership2`, `leadership3`, `leadership4`, `leadership5`, `leadership6`, `created_by`, `created_date`, `updated_by`, `updated_date`, `periode`, `comment_a1`, `comment_a2`, `comment_a3`, `total_culture`, `total_leadership`, `rating_a1`, `rating_a2`, `rating_a3`, `promotion`) VALUES
	(1, 3351, '', 'a', 5, '', 0, '', 0, '', 0, '', 0, 5.00, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3351, '2023-10-16 16:15:03', NULL, NULL, '2023', '', NULL, NULL, 0.00, 0.00, 0.00, NULL, NULL, 'N'),
	(2, 51321, 'managerial', 'objective 1', 4, 'objective 2', 5, '', 0, '', 0, '', 0, 4.50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 51321, '2023-10-17 11:36:34', NULL, NULL, '2023', '', NULL, NULL, 0.00, 0.00, 0.00, NULL, NULL, 'N'),
	(3, 4491, 'staff', 'HCIS', 5, 'Darwinbox', 5, '', 0, '', 0, '', 0, 5.00, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4491, '2023-10-17 14:17:05', NULL, NULL, '2023', '', NULL, NULL, 0.00, 0.00, 0.00, NULL, NULL, '');

-- Dumping structure for table pa_2023.transaksi_2023_peers
CREATE TABLE IF NOT EXISTS `transaksi_2023_peers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idkar` bigint(20) NOT NULL,
  `fortable` varchar(20) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `peers` bigint(20) NOT NULL DEFAULT 0,
  `value_1` text COLLATE latin1_general_ci NOT NULL,
  `score_1` int(1) NOT NULL DEFAULT 0,
  `value_2` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_2` int(1) DEFAULT NULL,
  `value_3` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_3` int(1) DEFAULT NULL,
  `value_4` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_4` int(1) DEFAULT NULL,
  `value_5` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_5` int(1) DEFAULT NULL,
  `total_score` decimal(4,2) DEFAULT NULL,
  `synergized1` int(1) DEFAULT NULL,
  `synergized2` int(1) DEFAULT NULL,
  `synergized3` int(1) DEFAULT NULL,
  `integrity1` int(1) DEFAULT NULL,
  `integrity2` int(1) DEFAULT NULL,
  `integrity3` int(1) DEFAULT NULL,
  `growth1` int(1) DEFAULT NULL,
  `growth2` int(1) DEFAULT NULL,
  `growth3` int(1) DEFAULT NULL,
  `adaptive1` int(1) DEFAULT NULL,
  `adaptive2` int(1) DEFAULT NULL,
  `adaptive3` int(1) DEFAULT NULL,
  `passion1` int(1) DEFAULT NULL,
  `passion2` int(1) DEFAULT NULL,
  `passion3` int(1) DEFAULT NULL,
  `leadership1` int(1) DEFAULT NULL,
  `leadership2` int(1) DEFAULT NULL,
  `leadership3` int(1) DEFAULT NULL,
  `leadership4` int(1) DEFAULT NULL,
  `leadership5` int(1) DEFAULT NULL,
  `leadership6` int(1) DEFAULT NULL,
  `created_by` bigint(20) NOT NULL,
  `created_date` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `updated_by` bigint(20) DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `periode` varchar(4) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `comment` text COLLATE latin1_general_ci DEFAULT NULL,
  `total_culture` decimal(4,2) DEFAULT NULL,
  `total_leadership` decimal(4,2) DEFAULT NULL,
  `rating` decimal(4,2) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table pa_2023.transaksi_2023_peers: ~0 rows (approximately)
REPLACE INTO `transaksi_2023_peers` (`id`, `idkar`, `fortable`, `peers`, `value_1`, `score_1`, `value_2`, `score_2`, `value_3`, `score_3`, `value_4`, `score_4`, `value_5`, `score_5`, `total_score`, `synergized1`, `synergized2`, `synergized3`, `integrity1`, `integrity2`, `integrity3`, `growth1`, `growth2`, `growth3`, `adaptive1`, `adaptive2`, `adaptive3`, `passion1`, `passion2`, `passion3`, `leadership1`, `leadership2`, `leadership3`, `leadership4`, `leadership5`, `leadership6`, `created_by`, `created_date`, `updated_by`, `updated_date`, `periode`, `comment`, `total_culture`, `total_leadership`, `rating`) VALUES
	(1, 51321, 'managerial', 50900, '', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 44051, '2023-10-17 06:43:20', NULL, NULL, '2023', NULL, NULL, NULL, NULL),
	(2, 51321, 'managerial', 50839, '', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 44051, '2023-10-17 06:43:20', NULL, NULL, '2023', NULL, NULL, NULL, NULL),
	(3, 51321, 'managerial', 51040, '', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 44051, '2023-10-17 06:43:20', NULL, NULL, '2023', NULL, NULL, NULL, NULL);

-- Dumping structure for table pa_2023.transaksi_2023_subo
CREATE TABLE IF NOT EXISTS `transaksi_2023_subo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idkar` bigint(20) NOT NULL,
  `fortable` varchar(20) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `value_1` text COLLATE latin1_general_ci NOT NULL,
  `score_1` int(1) NOT NULL DEFAULT 0,
  `value_2` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_2` int(1) DEFAULT NULL,
  `value_3` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_3` int(1) DEFAULT NULL,
  `value_4` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_4` int(1) DEFAULT NULL,
  `value_5` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_5` int(1) DEFAULT NULL,
  `total_score` decimal(4,2) DEFAULT NULL,
  `synergized1` int(1) DEFAULT NULL,
  `synergized2` int(1) DEFAULT NULL,
  `synergized3` int(1) DEFAULT NULL,
  `integrity1` int(1) DEFAULT NULL,
  `integrity2` int(1) DEFAULT NULL,
  `integrity3` int(1) DEFAULT NULL,
  `growth1` int(1) DEFAULT NULL,
  `growth2` int(1) DEFAULT NULL,
  `growth3` int(1) DEFAULT NULL,
  `adaptive1` int(1) DEFAULT NULL,
  `adaptive2` int(1) DEFAULT NULL,
  `adaptive3` int(1) DEFAULT NULL,
  `passion1` int(1) DEFAULT NULL,
  `passion2` int(1) DEFAULT NULL,
  `passion3` int(1) DEFAULT NULL,
  `leadership1` int(1) DEFAULT NULL,
  `leadership2` int(1) DEFAULT NULL,
  `leadership3` int(1) DEFAULT NULL,
  `leadership4` int(1) DEFAULT NULL,
  `leadership5` int(1) DEFAULT NULL,
  `leadership6` int(1) DEFAULT NULL,
  `created_by` bigint(20) NOT NULL,
  `created_date` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `updated_by` bigint(20) DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `periode` varchar(4) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `comment` text COLLATE latin1_general_ci DEFAULT NULL,
  `total_culture` decimal(4,2) DEFAULT NULL,
  `total_leadership` decimal(4,2) DEFAULT NULL,
  `rating` decimal(4,2) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table pa_2023.transaksi_2023_subo: ~0 rows (approximately)

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
