-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.4.24-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.3.0.6589
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table pa_2023.question_pa
CREATE TABLE IF NOT EXISTS `question_pa` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(30) COLLATE latin1_general_ci DEFAULT NULL,
  `group` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `title` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `title_en` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `item` text COLLATE latin1_general_ci DEFAULT NULL,
  `item_en` text COLLATE latin1_general_ci DEFAULT NULL,
  `role` varchar(15) COLLATE latin1_general_ci NOT NULL DEFAULT 'all',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

-- Dumping data for table pa_2023.question_pa: ~26 rows (approximately)
REPLACE INTO `question_pa` (`id`, `name`, `group`, `title`, `title_en`, `item`, `item_en`, `role`) VALUES
	(2, 'synergized', 'culture', 'SYNERGIZED TEAM', NULL, 'Berkomunikasi, sharing ide/pemikiran secara jelas dan efektif baik dengan lisan maupun tulisan', NULL, 'all'),
	(3, 'synergized', 'culture', 'SYNERGIZED TEAM', NULL, 'Bersedia mendedikasikan waktu dan tenaganya secara ekstra membantu perusahaan', NULL, 'all'),
	(4, 'synergized', 'culture', 'SYNERGIZED TEAM', NULL, 'Bekerja sama dan berpartisipasi aktif dalam kelompok kerja', NULL, 'all'),
	(5, 'integrity', 'culture', 'INTEGRITY FOR ALL ACTION', NULL, 'Dipercaya dapat menyelesaikan tugas dengan baik', NULL, 'all'),
	(6, 'integrity', 'culture', 'INTEGRITY FOR ALL ACTION', NULL, 'Berani bertanggung jawab atas ucapan dan tindakan yang diambil', NULL, 'all'),
	(7, 'integrity', 'culture', 'INTEGRITY FOR ALL ACTION', NULL, 'Menyelaraskan sikap dengan nilai perusahaan co : disiplin dan komitmen menjalankan peraturan perusahaan ', NULL, 'all'),
	(8, 'growth', 'culture', 'GROWTH FOR CO PROSPERITY', NULL, 'Mengutamakan keberhasilan bersama (tim)', NULL, 'all'),
	(9, 'growth', 'culture', 'GROWTH FOR CO PROSPERITY', NULL, 'Saling menghormati dan menghargai perbedaan pendapat dan sikap', NULL, 'all'),
	(10, 'growth', 'culture', 'GROWTH FOR CO PROSPERITY', NULL, 'Efisien dan Efektif dalam bekerja', NULL, 'all'),
	(11, 'adaptive', 'culture', 'ADAPTIVE TO CHANGE', NULL, 'Melahirkan gagasan baru yang tepat', NULL, 'all'),
	(12, 'adaptive', 'culture', 'ADAPTIVE TO CHANGE', NULL, 'Berkeinginan  kuat untuk mempelajari atau mengetahui hal baru berkaitan dengan pekerjaan', NULL, 'all'),
	(13, 'adaptive', 'culture', 'ADAPTIVE TO CHANGE', NULL, 'Memanfaatkan peluang dengan positif', NULL, 'all'),
	(14, 'passion', 'culture', 'PASSION FOR EXCELLENCE', NULL, 'Dorongan keinginan meningkatkan hasil kerja', NULL, 'all'),
	(15, 'passion', 'culture', 'PASSION FOR EXCELLENCE', NULL, 'Konsisten menerapkan profesionalisme', NULL, 'all'),
	(16, 'passion', 'culture', 'PASSION FOR EXCELLENCE', NULL, 'Mengembangkan pengetahuan / keahlian / metode kerja untuk kemajuan perusahaan', NULL, 'all'),
	(17, 'leadership', 'leadership', 'Komunikasi', 'Communication', 'Berbicara dan berdiskusi secara efektif, mengajak dan menginspirasi orang lain.', NULL, 'staffb'),
	(18, 'leadership', 'leadership', 'Perencanaan Kerja', 'Work Planning', 'Merencanakan kerja, sumber daya dan mengelola sumber daya, mengutamakan pekerjaan dan mengantisipasi potensi masalah dengan tujuan penyelesaian tugas atau project dengan tepat waktu.Mempertimbangkan kemampuannya untuk mengelola beberapa tugas atau project secara simultan (bersamaan).', NULL, 'staffb'),
	(19, 'leadership', 'leadership', 'Pembinaan', 'Coaching', 'Membina dan mengembangkan orang lain.', NULL, 'staffb'),
	(20, 'leadership', 'leadership', 'Pemecahan Masalah', 'Problem Solving', 'Menerapkan pendekatan yang terstruktur untuk mengevaluasi masalah dan situasi yang rumit.', NULL, 'staffb'),
	(21, 'leadership', 'leadership', 'Panutan', 'Role Model', 'Memiliki sikap dan perilaku: disiplin dan rasa memiliki terhadap Perusahaan yang patut untuk ditiru bawahan maupun rekan kerjanya.', NULL, 'staffb'),
	(22, 'leadership', 'leadership', 'Komunikasi', 'Communication', 'Berbicara dan berdiskusi secara efektif, mengajak dan menginspirasi orang lain.', NULL, 'managerial'),
	(23, 'leadership', 'leadership', 'Perencanaan Kerja', 'Work Planning', 'Merencanakan kerja, sumber daya dan mengelola sumber daya, mengutamakan pekerjaan dan mengantisipasi potensi masalah dengan tujuan penyelesaian tugas atau project dengan tepat waktu.Mempertimbangkan kemampuannya untuk mengelola beberapa tugas atau project secara simultan (bersamaan).', NULL, 'managerial'),
	(24, 'leadership', 'leadership', 'Pembinaan', 'Coaching', 'Membina dan mengembangkan orang lain.', NULL, 'managerial'),
	(25, 'leadership', 'leadership', 'Pemecahan Masalah', 'Problem Solving', 'Menerapkan pendekatan yang terstruktur untuk mengevaluasi masalah dan situasi yang rumit.', NULL, 'managerial'),
	(26, 'leadership', 'leadership', 'Panutan', 'Role Model', 'Memiliki sikap dan perilaku: disiplin dan rasa memiliki terhadap Perusahaan yang patut untuk ditiru bawahan maupun rekan kerjanya.', NULL, 'managerial'),
	(27, 'leadership', 'leadership', 'Pengembangan Orang', 'People Development', 'Membina dan mengembangkan orang lain.', NULL, 'managerial');

-- Dumping structure for table pa_2023.transaksi_2023
CREATE TABLE IF NOT EXISTS `transaksi_2023` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idkar` bigint(20) NOT NULL,
  `value_1` text COLLATE latin1_general_ci NOT NULL,
  `score_1` int(1) NOT NULL DEFAULT 0,
  `value_2` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_2` int(1) DEFAULT NULL,
  `value_3` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_3` int(1) DEFAULT NULL,
  `value_4` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_4` int(1) DEFAULT NULL,
  `value_5` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_5` int(1) DEFAULT NULL,
  `total_score` decimal(4,2) DEFAULT NULL,
  `synergized1` int(1) DEFAULT NULL,
  `synergized2` int(1) DEFAULT NULL,
  `synergized3` int(1) DEFAULT NULL,
  `integrity1` int(1) DEFAULT NULL,
  `integrity2` int(1) DEFAULT NULL,
  `integrity3` int(1) DEFAULT NULL,
  `growth1` int(1) DEFAULT NULL,
  `growth2` int(1) DEFAULT NULL,
  `growth3` int(1) DEFAULT NULL,
  `adaptive1` int(1) DEFAULT NULL,
  `adaptive2` int(1) DEFAULT NULL,
  `adaptive3` int(1) DEFAULT NULL,
  `passion1` int(1) DEFAULT NULL,
  `passion2` int(1) DEFAULT NULL,
  `passion3` int(1) DEFAULT NULL,
  `leadership1` int(1) DEFAULT NULL,
  `leadership2` int(1) DEFAULT NULL,
  `leadership3` int(1) DEFAULT NULL,
  `leadership4` int(1) DEFAULT NULL,
  `leadership5` int(1) DEFAULT NULL,
  `leadership6` int(1) DEFAULT NULL,
  `created_by` bigint(20) NOT NULL,
  `created_date` datetime NOT NULL,
  `updated_by` bigint(20) DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `periode` varchar(4) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `comment_a1` text COLLATE latin1_general_ci DEFAULT NULL,
  `comment_a2` text COLLATE latin1_general_ci DEFAULT NULL,
  `comment_a3` text COLLATE latin1_general_ci DEFAULT NULL,
  `total_culture` decimal(4,2) DEFAULT 0.00,
  `total_leadership` decimal(4,2) DEFAULT 0.00,
  `rating_a1` decimal(4,2) DEFAULT NULL,
  `rating_a2` decimal(4,2) DEFAULT NULL,
  `rating_a3` decimal(4,2) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table pa_2023.transaksi_2023: ~2 rows (approximately)

-- Dumping structure for table pa_2023.transaksi_2023_a1
CREATE TABLE IF NOT EXISTS `transaksi_2023_a1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idkar` bigint(20) NOT NULL,
  `value_1` text COLLATE latin1_general_ci NOT NULL,
  `score_1` int(1) NOT NULL DEFAULT 0,
  `value_2` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_2` int(1) DEFAULT NULL,
  `value_3` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_3` int(1) DEFAULT NULL,
  `value_4` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_4` int(1) DEFAULT NULL,
  `value_5` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_5` int(1) DEFAULT NULL,
  `total_score` decimal(4,2) DEFAULT NULL,
  `synergized1` int(1) DEFAULT NULL,
  `synergized2` int(1) DEFAULT NULL,
  `synergized3` int(1) DEFAULT NULL,
  `integrity1` int(1) DEFAULT NULL,
  `integrity2` int(1) DEFAULT NULL,
  `integrity3` int(1) DEFAULT NULL,
  `growth1` int(1) DEFAULT NULL,
  `growth2` int(1) DEFAULT NULL,
  `growth3` int(1) DEFAULT NULL,
  `adaptive1` int(1) DEFAULT NULL,
  `adaptive2` int(1) DEFAULT NULL,
  `adaptive3` int(1) DEFAULT NULL,
  `passion1` int(1) DEFAULT NULL,
  `passion2` int(1) DEFAULT NULL,
  `passion3` int(1) DEFAULT NULL,
  `leadership1` int(1) DEFAULT NULL,
  `leadership2` int(1) DEFAULT NULL,
  `leadership3` int(1) DEFAULT NULL,
  `leadership4` int(1) DEFAULT NULL,
  `leadership5` int(1) DEFAULT NULL,
  `leadership6` int(1) DEFAULT NULL,
  `created_by` bigint(20) NOT NULL,
  `created_date` datetime NOT NULL,
  `updated_by` bigint(20) DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `periode` varchar(4) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `comment_a1` text COLLATE latin1_general_ci DEFAULT NULL,
  `comment_a2` text COLLATE latin1_general_ci DEFAULT NULL,
  `comment_a3` text COLLATE latin1_general_ci DEFAULT NULL,
  `total_culture` decimal(4,2) DEFAULT 0.00,
  `total_leadership` decimal(4,2) DEFAULT 0.00,
  `rating_a1` decimal(4,2) DEFAULT NULL,
  `rating_a2` decimal(4,2) DEFAULT NULL,
  `rating_a3` decimal(4,2) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table pa_2023.transaksi_2023_a1: ~0 rows (approximately)

-- Dumping structure for table pa_2023.transaksi_2023_a2
CREATE TABLE IF NOT EXISTS `transaksi_2023_a2` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idkar` bigint(20) NOT NULL,
  `value_1` text COLLATE latin1_general_ci NOT NULL,
  `score_1` int(1) NOT NULL DEFAULT 0,
  `value_2` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_2` int(1) DEFAULT NULL,
  `value_3` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_3` int(1) DEFAULT NULL,
  `value_4` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_4` int(1) DEFAULT NULL,
  `value_5` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_5` int(1) DEFAULT NULL,
  `total_score` decimal(4,2) DEFAULT NULL,
  `synergized1` int(1) DEFAULT NULL,
  `synergized2` int(1) DEFAULT NULL,
  `synergized3` int(1) DEFAULT NULL,
  `integrity1` int(1) DEFAULT NULL,
  `integrity2` int(1) DEFAULT NULL,
  `integrity3` int(1) DEFAULT NULL,
  `growth1` int(1) DEFAULT NULL,
  `growth2` int(1) DEFAULT NULL,
  `growth3` int(1) DEFAULT NULL,
  `adaptive1` int(1) DEFAULT NULL,
  `adaptive2` int(1) DEFAULT NULL,
  `adaptive3` int(1) DEFAULT NULL,
  `passion1` int(1) DEFAULT NULL,
  `passion2` int(1) DEFAULT NULL,
  `passion3` int(1) DEFAULT NULL,
  `leadership1` int(1) DEFAULT NULL,
  `leadership2` int(1) DEFAULT NULL,
  `leadership3` int(1) DEFAULT NULL,
  `leadership4` int(1) DEFAULT NULL,
  `leadership5` int(1) DEFAULT NULL,
  `leadership6` int(1) DEFAULT NULL,
  `created_by` bigint(20) NOT NULL,
  `created_date` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `updated_by` bigint(20) DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `periode` varchar(4) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `comment_a1` text COLLATE latin1_general_ci DEFAULT NULL,
  `comment_a2` text COLLATE latin1_general_ci DEFAULT NULL,
  `comment_a3` text COLLATE latin1_general_ci DEFAULT NULL,
  `total_culture` decimal(4,2) DEFAULT NULL,
  `total_leadership` decimal(4,2) DEFAULT NULL,
  `rating_a1` decimal(4,2) DEFAULT NULL,
  `rating_a2` decimal(4,2) DEFAULT NULL,
  `rating_a3` decimal(4,2) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table pa_2023.transaksi_2023_a2: ~1 rows (approximately)

-- Dumping structure for table pa_2023.transaksi_2023_a3
CREATE TABLE IF NOT EXISTS `transaksi_2023_a3` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idkar` bigint(20) NOT NULL,
  `value_1` text COLLATE latin1_general_ci NOT NULL,
  `score_1` int(1) NOT NULL DEFAULT 0,
  `value_2` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_2` int(1) DEFAULT NULL,
  `value_3` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_3` int(1) DEFAULT NULL,
  `value_4` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_4` int(1) DEFAULT NULL,
  `value_5` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_5` int(1) DEFAULT NULL,
  `total_score` decimal(4,2) DEFAULT NULL,
  `synergized1` int(1) DEFAULT NULL,
  `synergized2` int(1) DEFAULT NULL,
  `synergized3` int(1) DEFAULT NULL,
  `integrity1` int(1) DEFAULT NULL,
  `integrity2` int(1) DEFAULT NULL,
  `integrity3` int(1) DEFAULT NULL,
  `growth1` int(1) DEFAULT NULL,
  `growth2` int(1) DEFAULT NULL,
  `growth3` int(1) DEFAULT NULL,
  `adaptive1` int(1) DEFAULT NULL,
  `adaptive2` int(1) DEFAULT NULL,
  `adaptive3` int(1) DEFAULT NULL,
  `passion1` int(1) DEFAULT NULL,
  `passion2` int(1) DEFAULT NULL,
  `passion3` int(1) DEFAULT NULL,
  `leadership1` int(1) DEFAULT NULL,
  `leadership2` int(1) DEFAULT NULL,
  `leadership3` int(1) DEFAULT NULL,
  `leadership4` int(1) DEFAULT NULL,
  `leadership5` int(1) DEFAULT NULL,
  `leadership6` int(1) DEFAULT NULL,
  `created_by` bigint(20) NOT NULL,
  `created_date` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `updated_by` bigint(20) DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `periode` varchar(4) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `comment_a1` text COLLATE latin1_general_ci DEFAULT NULL,
  `comment_a2` text COLLATE latin1_general_ci DEFAULT NULL,
  `comment_a3` text COLLATE latin1_general_ci DEFAULT NULL,
  `total_culture` decimal(4,2) DEFAULT NULL,
  `total_leadership` decimal(4,2) DEFAULT NULL,
  `rating_a1` decimal(4,2) DEFAULT NULL,
  `rating_a2` decimal(4,2) DEFAULT NULL,
  `rating_a3` decimal(4,2) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table pa_2023.transaksi_2023_a3: ~0 rows (approximately)

-- Dumping structure for table pa_2023.transaksi_2023_awal
CREATE TABLE IF NOT EXISTS `transaksi_2023_awal` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idkar` bigint(20) NOT NULL,
  `value_1` text COLLATE latin1_general_ci NOT NULL,
  `score_1` int(1) NOT NULL DEFAULT 0,
  `value_2` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_2` int(1) DEFAULT NULL,
  `value_3` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_3` int(1) DEFAULT NULL,
  `value_4` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_4` int(1) DEFAULT NULL,
  `value_5` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_5` int(1) DEFAULT NULL,
  `total_score` decimal(4,2) DEFAULT NULL,
  `synergized1` int(1) DEFAULT NULL,
  `synergized2` int(1) DEFAULT NULL,
  `synergized3` int(1) DEFAULT NULL,
  `integrity1` int(1) DEFAULT NULL,
  `integrity2` int(1) DEFAULT NULL,
  `integrity3` int(1) DEFAULT NULL,
  `growth1` int(1) DEFAULT NULL,
  `growth2` int(1) DEFAULT NULL,
  `growth3` int(1) DEFAULT NULL,
  `adaptive1` int(1) DEFAULT NULL,
  `adaptive2` int(1) DEFAULT NULL,
  `adaptive3` int(1) DEFAULT NULL,
  `passion1` int(1) DEFAULT NULL,
  `passion2` int(1) DEFAULT NULL,
  `passion3` int(1) DEFAULT NULL,
  `leadership1` int(1) DEFAULT NULL,
  `leadership2` int(1) DEFAULT NULL,
  `leadership3` int(1) DEFAULT NULL,
  `leadership4` int(1) DEFAULT NULL,
  `leadership5` int(1) DEFAULT NULL,
  `leadership6` int(1) DEFAULT NULL,
  `created_by` bigint(20) NOT NULL,
  `created_date` datetime NOT NULL,
  `updated_by` bigint(20) DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `periode` varchar(4) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `comment_a1` text COLLATE latin1_general_ci DEFAULT NULL,
  `comment_a2` text COLLATE latin1_general_ci DEFAULT NULL,
  `comment_a3` text COLLATE latin1_general_ci DEFAULT NULL,
  `total_culture` decimal(4,2) DEFAULT 0.00,
  `total_leadership` decimal(4,2) DEFAULT 0.00,
  `rating_a1` decimal(4,2) DEFAULT NULL,
  `rating_a2` decimal(4,2) DEFAULT NULL,
  `rating_a3` decimal(4,2) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table pa_2023.transaksi_2023_awal: ~0 rows (approximately)

-- Dumping structure for table pa_2023.transaksi_2023_peers
CREATE TABLE IF NOT EXISTS `transaksi_2023_peers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idkar` bigint(20) NOT NULL,
  `peers` bigint(20) NOT NULL DEFAULT 0,
  `value_1` text COLLATE latin1_general_ci NOT NULL,
  `score_1` int(1) NOT NULL DEFAULT 0,
  `value_2` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_2` int(1) DEFAULT NULL,
  `value_3` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_3` int(1) DEFAULT NULL,
  `value_4` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_4` int(1) DEFAULT NULL,
  `value_5` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_5` int(1) DEFAULT NULL,
  `total_score` decimal(4,2) DEFAULT NULL,
  `synergized1` int(1) DEFAULT NULL,
  `synergized2` int(1) DEFAULT NULL,
  `synergized3` int(1) DEFAULT NULL,
  `integrity1` int(1) DEFAULT NULL,
  `integrity2` int(1) DEFAULT NULL,
  `integrity3` int(1) DEFAULT NULL,
  `growth1` int(1) DEFAULT NULL,
  `growth2` int(1) DEFAULT NULL,
  `growth3` int(1) DEFAULT NULL,
  `adaptive1` int(1) DEFAULT NULL,
  `adaptive2` int(1) DEFAULT NULL,
  `adaptive3` int(1) DEFAULT NULL,
  `passion1` int(1) DEFAULT NULL,
  `passion2` int(1) DEFAULT NULL,
  `passion3` int(1) DEFAULT NULL,
  `leadership1` int(1) DEFAULT NULL,
  `leadership2` int(1) DEFAULT NULL,
  `leadership3` int(1) DEFAULT NULL,
  `leadership4` int(1) DEFAULT NULL,
  `leadership5` int(1) DEFAULT NULL,
  `leadership6` int(1) DEFAULT NULL,
  `created_by` bigint(20) NOT NULL,
  `created_date` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `updated_by` bigint(20) DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `periode` varchar(4) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `comment` text COLLATE latin1_general_ci DEFAULT NULL,
  `total_culture` decimal(4,2) DEFAULT NULL,
  `total_leadership` decimal(4,2) DEFAULT NULL,
  `rating` decimal(4,2) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table pa_2023.transaksi_2023_peers: ~0 rows (approximately)

-- Dumping structure for table pa_2023.transaksi_2023_subo
CREATE TABLE IF NOT EXISTS `transaksi_2023_subo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idkar` bigint(20) NOT NULL,
  `value_1` text COLLATE latin1_general_ci NOT NULL,
  `score_1` int(1) NOT NULL DEFAULT 0,
  `value_2` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_2` int(1) DEFAULT NULL,
  `value_3` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_3` int(1) DEFAULT NULL,
  `value_4` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_4` int(1) DEFAULT NULL,
  `value_5` text COLLATE latin1_general_ci DEFAULT NULL,
  `score_5` int(1) DEFAULT NULL,
  `total_score` decimal(4,2) DEFAULT NULL,
  `synergized1` int(1) DEFAULT NULL,
  `synergized2` int(1) DEFAULT NULL,
  `synergized3` int(1) DEFAULT NULL,
  `integrity1` int(1) DEFAULT NULL,
  `integrity2` int(1) DEFAULT NULL,
  `integrity3` int(1) DEFAULT NULL,
  `growth1` int(1) DEFAULT NULL,
  `growth2` int(1) DEFAULT NULL,
  `growth3` int(1) DEFAULT NULL,
  `adaptive1` int(1) DEFAULT NULL,
  `adaptive2` int(1) DEFAULT NULL,
  `adaptive3` int(1) DEFAULT NULL,
  `passion1` int(1) DEFAULT NULL,
  `passion2` int(1) DEFAULT NULL,
  `passion3` int(1) DEFAULT NULL,
  `leadership1` int(1) DEFAULT NULL,
  `leadership2` int(1) DEFAULT NULL,
  `leadership3` int(1) DEFAULT NULL,
  `leadership4` int(1) DEFAULT NULL,
  `leadership5` int(1) DEFAULT NULL,
  `leadership6` int(1) DEFAULT NULL,
  `created_by` bigint(20) NOT NULL,
  `created_date` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `updated_by` bigint(20) DEFAULT NULL,
  `updated_date` datetime DEFAULT NULL,
  `periode` varchar(4) COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `comment` text COLLATE latin1_general_ci DEFAULT NULL,
  `total_culture` decimal(4,2) DEFAULT NULL,
  `total_leadership` decimal(4,2) DEFAULT NULL,
  `rating` decimal(4,2) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci ROW_FORMAT=DYNAMIC;

-- Dumping data for table pa_2023.transaksi_2023_subo: ~0 rows (approximately)

-- Dumping structure for table pa_2023.user_pa
CREATE TABLE IF NOT EXISTS `user_pa` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pic` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `jabatan` varchar(50) COLLATE latin1_general_ci DEFAULT 'User',
  `since` varchar(50) COLLATE latin1_general_ci DEFAULT '2019',
  `profile` varchar(50) COLLATE latin1_general_ci DEFAULT 'profile.png',
  `email` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `nik_baru` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `username` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `password` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `lastip` varchar(50) COLLATE latin1_general_ci DEFAULT NULL,
  `lastlogin` datetime DEFAULT NULL,
  `active` enum('Y','N') COLLATE latin1_general_ci DEFAULT 'Y',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=51322 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

-- Dumping data for table pa_2023.user_pa: ~10 rows (approximately)
REPLACE INTO `user_pa` (`id`, `pic`, `jabatan`, `since`, `profile`, `email`, `nik_baru`, `username`, `password`, `lastip`, `lastlogin`, `active`) VALUES
	(1, 'Test', 'User', '2019', 'profile.png', 'eriton.dewa@kpnplantation.com', 'eriton', 'eriton', '7b4d89998902caf489b0531c62525bed', '172.30.2.79', '2022-10-31 08:28:53', 'Y'),
	(2, 'OD', 'User', '2019', 'profile.png', NULL, 'deptod', 'deptod', 'ec028a30c5d949fe8548cf244639584c', '192.168.100.1', '2019-11-27 13:35:49', 'Y'),
	(3351, 'Retno Hastomo', 'User', '2019', 'profile.png', 'ritno.hastomo@kpnplantation.com', '01115050007', '15-05-746-0180', '5f1e2787f6281e6160ce325d133457d9', '127.0.0.1', '2023-10-13 18:09:33', 'Y'),
	(3770, 'Subani', 'User', '2019', 'profile.png', NULL, NULL, '17-09-710-0198', '5f1e2787f6281e6160ce325d133457d9', '127.0.0.1', '2023-10-16 09:45:16', 'Y'),
	(4491, 'Eriton Latti Dewa', 'User', '2022', 'profile.png', 'eriton.dewa@kpnplantation.com', '01119060003', '19-06-621-0174', '5f1e2787f6281e6160ce325d133457d9', '127.0.0.1', '2023-10-10 17:49:49', 'Y'),
	(6242, 'Hendri Saksti', 'User', '2019', 'profile.png', NULL, NULL, 'APB00098', '5f1e2787f6281e6160ce325d133457d9', NULL, NULL, 'Y'),
	(44051, 'Budi Setiono', 'User', '2019', 'profile.png', NULL, '01122100006', '22-10-759-6909', '5f1e2787f6281e6160ce325d133457d9', '127.0.0.1', '2023-10-16 10:10:40', 'Y'),
	(50900, 'Agusnadi', 'User', '2019', 'profile.png', NULL, NULL, '23-02-313-0128', '5f1e2787f6281e6160ce325d133457d9', '127.0.0.1', '2023-10-16 13:33:44', 'Y'),
	(50914, 'Jacqueline Sitorus', 'User', '2019', 'profile.png', NULL, NULL, '12-01-701-1224', '5f1e2787f6281e6160ce325d133457d9', '127.0.0.1', '2023-10-12 16:22:49', 'Y'),
	(51321, 'Rolles Herwin Sihombing', 'User', '2019', 'profile.png', NULL, NULL, '23-07-303-0487', '5f1e2787f6281e6160ce325d133457d9', '127.0.0.1', '2023-10-16 10:03:01', 'Y');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
